apiVersion: shipwright.io/v1beta1
kind: BuildRun
metadata:
  generateName: cc-server-buildpacks-run-
  namespace: cc-week10
spec:
  build:
    name: cc-server-buildpacks
  output:
    image: docker.io/REGISTRY_USERNAME/cc-server:2.0.0
    pushSecret: dockerhub-secret
