apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: cc-server-kaniko
  namespace: cc-week10
spec:
  source:
    type: Git
    git:
      url: https://github.com/qu1queee/sample-app
      revision: qu1queee/week10
  strategy:
    name: kaniko
    kind: ClusterBuildStrategy
  output:
    image: docker.io/REGISTRY_USERNAME/cc-server-kaniko:1.0.0
    pushSecret: dockerhub-secret
