FROM golang:1.23-bookworm
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
ARG VERSION=dev
# TODO: compile the binary; inject VERSION into main.version using -ldflags; name the output binary "server"
RUN # ???
EXPOSE 8080
# TODO: run the server binary
CMD # ???
