apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cc-data
  namespace: cc-week09
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
