apiVersion: v1
kind: Secret
metadata:
  name: cc-secret
  namespace: cc-week08
type: Opaque
data:
  # base64-encoded values — decode with: echo "<value>" | base64 --decode
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  API_KEY: c3VwZXJzZWNyZXRrZXk=
